version: '3'

services:

  account-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: account-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/account-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - accountservice_network
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: account-service
    networks:
      - accountservice_network
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  accountservice_network:
    driver: bridge

volumes:
  postgres: